export interface Language {
  code: string
  name: string
  nativeName: string
  countryCode: string
}

export const LANGUAGES: Language[] = [
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", countryCode: "za" },
  { code: "sq", name: "Albanian", nativeName: "Shqip", countryCode: "al" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", countryCode: "et" },
  { code: "ar", name: "Arabic", nativeName: "العربية", countryCode: "sa" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", countryCode: "am" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan", countryCode: "az" },
  { code: "eu", name: "Basque", nativeName: "Euskara", countryCode: "es" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская", countryCode: "by" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", countryCode: "bd" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski", countryCode: "ba" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", countryCode: "bg" },
  { code: "ca", name: "Catalan", nativeName: "Català", countryCode: "es" },
  { code: "ceb", name: "Cebuano", nativeName: "Cebuano", countryCode: "ph" },
  { code: "zh", name: "Chinese (Simplified)", nativeName: "中文 (简体)", countryCode: "cn" },
  { code: "zh-TW", name: "Chinese (Traditional)", nativeName: "中文 (繁體)", countryCode: "tw" },
  { code: "co", name: "Corsican", nativeName: "Corsu", countryCode: "fr" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", countryCode: "hr" },
  { code: "cs", name: "Czech", nativeName: "Čeština", countryCode: "cz" },
  { code: "da", name: "Danish", nativeName: "Dansk", countryCode: "dk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", countryCode: "nl" },
  { code: "en", name: "English", nativeName: "English", countryCode: "gb" },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto", countryCode: "eu" },
  { code: "et", name: "Estonian", nativeName: "Eesti", countryCode: "ee" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", countryCode: "fi" },
  { code: "fr", name: "French", nativeName: "Français", countryCode: "fr" },
  { code: "fy", name: "Frisian", nativeName: "Frysk", countryCode: "nl" },
  { code: "gl", name: "Galician", nativeName: "Galego", countryCode: "es" },
  { code: "ka", name: "Georgian", nativeName: "ქართული", countryCode: "ge" },
  { code: "de", name: "German", nativeName: "Deutsch", countryCode: "de" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", countryCode: "gr" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", countryCode: "in" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen", countryCode: "ht" },
  { code: "ha", name: "Hausa", nativeName: "Hausa", countryCode: "ng" },
  { code: "haw", name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi", countryCode: "us" },
  { code: "he", name: "Hebrew", nativeName: "עברית", countryCode: "il" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", countryCode: "in" },
  { code: "hmn", name: "Hmong", nativeName: "Hmong", countryCode: "cn" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", countryCode: "hu" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", countryCode: "is" },
  { code: "ig", name: "Igbo", nativeName: "Igbo", countryCode: "ng" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", countryCode: "id" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", countryCode: "ie" },
  { code: "it", name: "Italian", nativeName: "Italiano", countryCode: "it" },
  { code: "ja", name: "Japanese", nativeName: "日本語", countryCode: "jp" },
  { code: "jv", name: "Javanese", nativeName: "Basa Jawa", countryCode: "id" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", countryCode: "in" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақ тілі", countryCode: "kz" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ", countryCode: "kh" },
  { code: "ko", name: "Korean", nativeName: "한국어", countryCode: "kr" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî", countryCode: "iq" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча", countryCode: "kg" },
  { code: "lo", name: "Lao", nativeName: "ລາວ", countryCode: "la" },
  { code: "la", name: "Latin", nativeName: "Latina", countryCode: "va" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", countryCode: "lv" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", countryCode: "lt" },
  { code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch", countryCode: "lu" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски", countryCode: "mk" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy", countryCode: "mg" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", countryCode: "my" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", countryCode: "in" },
  { code: "mt", name: "Maltese", nativeName: "Malti", countryCode: "mt" },
  { code: "mi", name: "Maori", nativeName: "Māori", countryCode: "nz" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", countryCode: "in" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол", countryCode: "mn" },
  { code: "my", name: "Myanmar (Burmese)", nativeName: "မြန်မာစာ", countryCode: "mm" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली", countryCode: "np" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", countryCode: "no" },
  { code: "ny", name: "Nyanja (Chichewa)", nativeName: "Chichewa", countryCode: "mw" },
  { code: "ps", name: "Pashto", nativeName: "پښتو", countryCode: "af" },
  { code: "fa", name: "Persian", nativeName: "فارسی", countryCode: "ir" },
  { code: "pl", name: "Polish", nativeName: "Polski", countryCode: "pl" },
  { code: "pt", name: "Portuguese", nativeName: "Português", countryCode: "pt" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", countryCode: "in" },
  { code: "ro", name: "Romanian", nativeName: "Română", countryCode: "ro" },
  { code: "ru", name: "Russian", nativeName: "Русский", countryCode: "ru" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa", countryCode: "ws" },
  { code: "gd", name: "Scots Gaelic", nativeName: "Gàidhlig", countryCode: "gb" },
  { code: "sr", name: "Serbian", nativeName: "Српски", countryCode: "rs" },
  { code: "st", name: "Sesotho", nativeName: "Sesotho", countryCode: "ls" },
  { code: "sn", name: "Shona", nativeName: "Shona", countryCode: "zw" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي", countryCode: "pk" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල", countryCode: "lk" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", countryCode: "sk" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", countryCode: "si" },
  { code: "so", name: "Somali", nativeName: "Soomaali", countryCode: "so" },
  { code: "es", name: "Spanish", nativeName: "Español", countryCode: "es" },
  { code: "su", name: "Sundanese", nativeName: "Basa Sunda", countryCode: "id" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", countryCode: "tz" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", countryCode: "se" },
  { code: "tl", name: "Tagalog (Filipino)", nativeName: "Tagalog", countryCode: "ph" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ", countryCode: "tj" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", countryCode: "in" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", countryCode: "in" },
  { code: "th", name: "Thai", nativeName: "ไทย", countryCode: "th" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", countryCode: "tr" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", countryCode: "ua" },
  { code: "ur", name: "Urdu", nativeName: "اردو", countryCode: "pk" },
  { code: "uz", name: "Uzbek", nativeName: "O'zbek", countryCode: "uz" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", countryCode: "vn" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg", countryCode: "gb" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa", countryCode: "za" },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש", countryCode: "il" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá", countryCode: "ng" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu", countryCode: "za" },
]
